### ISSUE TITLE
Document that transactions may be lost in the event of unclean shutdown

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/parity-db#10]
This is not standard behavior for databases, although it makes sense in the context of ParityDB, where lost data can be restored from other nodes.

**Comment by arkpar** [comment]
Documented here: https://github.com/paritytech/parity-db/blob/master/src/options.rs#L31
Most embedded key-value stores, such as LevelDB or RocksDB also have fsync-durability off by default.
