### ISSUE TITLE
Slice indexation error after BTree header write failure

### ISSUE THREAD

**Issue by Tpt** [paritytech/parity-db#114]
First bug uncovered thanks to #113.

When a partial write happens after opening the database with a single BTree the iteration fails on the following db opening with `'range end index 8 out of range for slice of length 0'` inside of `Entry::read_slice` nested in `BTreeTable::btree_header`.

Reproduction test (requires #113 and the enabeling of the `instrumentation` feature):
```rust
	#[test]
	fn test_from_fuzzer() {
		crate::set_number_of_allowed_io_operations(12);
		let tmp = tempdir().unwrap();
		let mut options = Options::with_columns(tmp.path(), 1);
		options.columns[0].btree_index = true;
		assert!(Db::open_or_create(&options).is_err()); //It's going to fail

		let db = Db::open_or_create(&options).unwrap();
		db.iter(0).unwrap(); //Read is panicking here
	}
```

**Comment by cheme** [comment]
The wal should prevent that, but I remember skipping the wal for some first time initialization of the header (only on the very first db opening), will check that next week.

**Comment by Tpt** [comment]
> I remember skipping the wal for some first time initialization of the header

Thank you ! It looks a lot like it.

**Comment by Tpt** [comment]
I had a deeper look it it. Fixing this cleanly by adding the header initialization to the log seems to require a significant refactoring to avoid piling up hacks.

@arkpar Is this something important to fix? The column initialization is likely to only happen at the database creation, hence at a step where there is no data to corrupt.

**Comment by cheme** [comment]
> Another option: handle write errors on initialization and cleanup (delete) the file properly if anything goes wrong, before propagating the error up.

I would maybe go in this direction (using log is a lot of work for something small and treating missing file header as empty header was a bit awkward iirc (like I did not want to have an api with bound check on file read, but maybe checking file size could have done the job and I just did not think of doing that at the time).

**Comment by Tpt** [comment]
> Another option: handle write errors on initialization and cleanup (delete) the file properly if anything goes wrong, before propagating the error up.

It sounds indeed a good way to go. Thank you!
