### ISSUE TITLE
crash_DB 

### ISSUE THREAD

**Issue by CNazar** [paritytech/parity-db#12]
in the event of an emergency shutdown of the virtual disk on the home computer (when the light turns off) in most cases there is a drop in the base (an attachment error is added). I understand that running the node on a home computer does not meet the requirements of the data center where uninterruptible power supply, but for statistics I send a report
https://ibb.co/yFhF8gq

vmware 14.1.4
ubuntu 18,04 lts
2cpu
3 GB
Hdd 80 gb

**Comment by arkpar** [comment]
It looks like you are using the default rocksdb backend and not parity-db.
Please report this in https://github.com/paritytech/substrate
