### ISSUE TITLE
Corruption: Missing btree entry at addr 45:61327

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/parity-db#131]
[Here](https://forum.subspace.network/t/failed-to-start-subspaced-farm/768) is one of our users reporting getting "Corruption: Missing btree entry at addr 45:61327" on ParityDb database. Keys and values are both 8 bytes in in one column and one 11 byte key with 8 bytes value in second column.

I suspect application was killed due to shutting down slowly by systemd, which is the type of interruption ParityDb claims to be handling:
> Database is restored to consistent state if IO is interrupted at any point.

I don't have much more details at the moment, but I hope this is helpful.

**Comment by arkpar** [comment]
cc @cheme

**Comment by cheme** [comment]
Thanks for the report, it's always good to be aware of such failure.
We did try fuzzing interrupt io and did some slight change, but nothing that match this issue (it was incorrect root at first db opening and blocked db on partial wal reading IIRC).

This really look like a partial write (a parent node updated but not its child), but out of hardware related issue, should indeed be properly handle by parity-db.
At this point I can think of three reasons here:
- bug in btree code (in this case it would be just bad luck that things did happen on a restart).
- wal log files deleted in parity db by the sytemd service (but there would probably be a lot of similar report in this case).
- system or hardware related incorrect fsync (I mean db writing to files with a wal that is not flushed).

**Comment by nazar-pc** [comment]
Hm... I'm now leaning towards a bug in btree, here is a CI failure in test with "Corruption: Missing btree entry at addr 45:11": https://github.com/subspace/subspace/actions/runs/3128533715/jobs/5076493992#step:7:1737

This is the first time I see a test failing with such an error.

**Comment by cheme** [comment]
I have a few additional question:
Did the test fail every time?
Did this test work with 0.3.16?
Is this test opening and closing db?
The failing run is on is on macos, did we have failure on linux or windows?

**Comment by nazar-pc** [comment]
> Did the test fail every time?

That is the first time ever I saw the test fail, in CI or otherwise.

>  Did this test work with 0.3.16?

Worked all the time before, including when we were on 0.3.16.

>  Is this test opening and closing db?

No, it creates a new database every time.

>  The failing run is on is on macos, did we have failure on linux or windows?

User report linked in the first comment is from Linux (with 99% probability either Ubuntu 20.04 or 22.04). So we have at least 2 platforms where this happens.

**Comment by arkpar** [comment]
I was able to unreliably reproduce this with `cargo test -p subspace-farmer test_dsn_sync` on macos. Definitely some kind of race condition. Here's the trace:
https://gist.github.com/arkpar/224f4b4f365896809fddeecb2faf773a

**Comment by cheme** [comment]
@arkpar , did you run on parity-db 0.3.17 (I also did see the error after a while of looping on the test and on linux)?
I am currently trying on parity-db master and don't have it yet, the only reason could be this change https://github.com/paritytech/parity-db/commit/2be973860d67254f6c96db7c916ea7b173f1fef9#r85146328 (the write_plan function was not needed and it may have make some case where both btree header are seen as the same). But for now this is really just an hypothesis.

**Comment by arkpar** [comment]
I've reproduced it with 0.3.17 indeed. After patching subspace to use parity-db master, I wasn't able to reproduce it as well. So that was probably it.

**Comment by cheme** [comment]
>  it may have make some case where both btree header are seen as the same

actually I misread the code, it is also changing the header in a same way as before, only difference is that we don't fetch root and rewrite root. But I did see this as not an issue when removing the code as root should be fetched updated from the log writer.

**Comment by cheme** [comment]
About the CI failure, it looks like it was iterator failing when record id change.
We did not observe this with master, and did publish 0.4.0 that contains a few breaking change.
Mainly need to switch the option like this (I did not see someplace in your code where the other change should be impacting):
```
diff --git a/crates/subspace-farmer/src/commitments/databases.rs b/crates/subspace-farmer/src/commitments/databases.rs
index f6c81523b..440bce4fa 100644
--- a/crates/subspace-farmer/src/commitments/databases.rs
+++ b/crates/subspace-farmer/src/commitments/databases.rs
@@ -94,12 +94,12 @@ impl CommitmentDatabases {
                         uniform: false,
                         ref_counted: false,
                         compression: CompressionType::NoCompression,
-                        compression_threshold: 4096,
                     }],
                     sync_wal: true,
                     sync_data: true,
                     stats: false,
                     salt: None,
+                   compression_threshold: vec![(0, 4096)].into_iter().collect(),
                 };
                 let db = Db::open_or_create(&options).map_err(CommitmentError::CommitmentDb)?;
                 databases.put(
```
at a few place.
