### ISSUE TITLE
Question: how a retrieve the raw key during DB iteration

### ISSUE THREAD

**Issue by hanabi1224** [paritytech/parity-db#187]
Hello, I have a scenario that requires iterating the database and retrieving the original key, but I could only find the hashed key from an `IterState`, my questions are

- Is it possible to retrieve the raw key during iteration? If so, how?
- DB iteration seems to be slower than I would expect, ~5 hours on a 200GB db with ~100M entries, is that expected? Is there any trick to improve that?

Looking forward to your reply, thanks in advance!

**Comment by arkpar** [comment]
Retrieving keys is only possible for columns configured with `btree_index=true`. For regular hash columns the key is not stored in the database. You'd need to store it along with the value or derive it from the value in some other way (e.g. by hashing the value).

> DB iteration seems to be slower than I would expect, ~5 hours on a 200GB db with ~100M entries, is that expected? Is there any trick to improve that?

For hash columns iteration involves a lot of small random reads. 5 hours is too much though. Is that on SSD? In any case, iteration for hash tables was mostly meant for debugging and not for any real use case. It can be optmized. Please file a separate issue if you really need this.

**Comment by hanabi1224** [comment]
Thanks
