### ISSUE TITLE
Make `find_entry_sse2` optional behind a feature

### ISSUE THREAD

**Issue by hanabi1224** [paritytech/parity-db#189]
Hello, I constantly getting lookup failures with keys that are supposed to exist in the DB with v0.4.4, after downgrading to v0.4.3 the issue is gone.  Unfortunately I'm not able to make a minimal repo cuz the DB I use is at ~200GB with 100M+ records, but I strongly suspect there's bug in `find_entry_sse2`.  Is there any chance to make it behind a cargo feature so that I can opt-out without disabling sse2 cpu-feature? Thanks

**Comment by arkpar** [comment]
If there is a bug we would rather prefer to fix it. Is there a way to reproduce the issue reliably? I've tried syncing the filecoin chain from a snapshot and doing `forest-cli snapshot export --dry-run` as described [here](https://github.com/ChainSafe/forest/pull/2648) but it does not produce any relevant output. 
Could you please provide more details?

**Comment by arkpar** [comment]
Feel free to reach us at https://matrix.to/#/!tAxdATpgectGTCTFAx:parity.io

**Comment by arkpar** [comment]
@hanabi1224 
On a side note: I've checked how parity-db is used in the forest projects and noted a few things:

1. On macos default file descriptor limit causes the database to fail at some point. You can raise on startup with `fdlimit` crate.
2. If you decrease commit size [here](https://github.com/ChainSafe/forest/blob/main/utils/genesis/src/lib.rs#L190) to something like 64Mb you'd get better performance and lower peak memory usage.
3. You can further increase compression by setting compression threshold in the column settings. Default is 4096 meaning that any values of lower size won't be compressed.

**Comment by hanabi1224** [comment]
@arkpar Thanks for the advice! Will test it out.
