### ISSUE TITLE
Potential index corruption on exit

### ISSUE THREAD

**Issue by jasl** [paritytech/parity-db#198]
I'm promoting our user (Phala) switch to ParityDB, then I got 3 dedicated reports that after a reboot (normal exit then restart I believe), the node is stuck on `Is collating: No`, according to `htop`, no IO, a CPU core is 100%, enable RUST_LOG="DEBUG" no extra info

A reporter just tries to delete all `index_` files, it seems those indexes are rebuilt, and the node is back to normal.

**Comment by arkpar** [comment]
What version of the parity-db crate is used in the project? Is there a way to reproduce this?

> A reporter just tries to delete all index_ files, it seems those indexes are rebuilt, and the node is back to normal.

This is basically equivalent to deleting the whole database.

**Comment by jasl** [comment]
> What version of the parity-db crate is used in the project? Is there a way to reproduce this?
> 
> > A reporter just tries to delete all index_ files, it seems those indexes are rebuilt, and the node is back to normal.
> 
> This is basically equivalent to deleting the whole database.

the latest version, 0.4.6

TBH, I tested paritydb on dozens of machines, with no issue, so I don't know how these users met the problem.

> This is basically equivalent to deleting the whole database.

Those indexes do seem not quite big, only ~ 2G, total DB are 47G

one of the reporters give me his bad indexes, I'm not sure it would help, could you help to exam it?

https://storage.googleapis.com/phala-misc/phala-node-db-index.zip

**Comment by jasl** [comment]
they're using

```
jasl123/phala-node-with-launcher:v0.1.23-dev.5
DIGEST:sha256:21e8b239dd12f9287832e135dae1a2262c9dbd83d026e9617d60d80a372b3e9d
```

The binary is based on https://github.com/Phala-Network/khala-parachain/pull/263

I already tested paritydb at least 6 months on dozens of machines, with no issue, so I'm not sure it can stably reproduce...

**Comment by wowvwow** [comment]
![image](https://user-images.githubusercontent.com/28591822/230626280-a9ce1e07-b308-45e6-ae43-264f401a647e.png)
![image](https://user-images.githubusercontent.com/28591822/230626329-6b2b3efa-4e38-4640-88e4-183f0c806bf1.png)
![image](https://user-images.githubusercontent.com/28591822/230626438-69822ead-9f37-44b5-a5ae-63550d1aea1c.png)
![image](https://user-images.githubusercontent.com/28591822/230627262-c1f21326-64b5-482f-9c2e-e52b77abcbfd.png)
After a period of intervals, about tens of minutes, or several hours later, after rebooting the system, the phala-node service starts to check the logs, and it will always be stuck without any log output. At the same time, the single-core cpu The performance reaches 100%, and there is no IO.

Then, after I stopped the phala-node service, after the index file, lock file, and metadata file under paritydb, mv became bak, and restarted phala-node, everything became better. Excuse me, what caused this?

This problem occurred this morning, and now, at night, after I rebooted the server, the bug reappeared

**Comment by arkpar** [comment]
It's hard to sat what's going on looking at screenshots.
You have a few "Address space overflow" errors as a result of deleting index files. 
In general, deleting index file won't do you any good, as it simply breaks internal database structure. If you have a way to reproduce the issue with a clean database, or a copy of the database that demonstrate the issue before any messing around with database files, that would be helpful. Otherwise there's not much we can do.

**Comment by jasl** [comment]
so the fix is https://github.com/paritytech/cumulus/pull/2461
so it's not ParityDB issue, but do you know why ParityDB impacts much? people switch back to RocksDB then everything seems to go well

I'll try to backport that and let users retry, if no issue, I'll close this issue

**Comment by jasl** [comment]
I just backported https://github.com/paritytech/cumulus/pull/2461 and confirm the node is no more stuck on boot.

Sorry for wasting your time, and thank you for your patience!
