### ISSUE TITLE
extreamly slow booting

### ISSUE THREAD

**Issue by jasl** [paritytech/parity-db#207]
Come from https://github.com/paritytech/substrate/issues/13947#issuecomment-1530938700

I'd catch nperf data from my Azure VM (premium SSD), and the node running in a Docker container, nperf running in the container too.

The current status is the node is stuck on booting, and it is not because of Cumulus reason, and the node is fresh sync last week (stop when speed reduced to 0 bps)

Here are flaming graphs I record the boot starting

![from_start_2](https://user-images.githubusercontent.com/1024162/235807779-87e9a5e7-9adc-4200-9358-5c391f961416.svg)
![from_start](https://user-images.githubusercontent.com/1024162/235807786-d2899950-def9-4f6f-a1df-80cc48974c40.svg)

[flaminggraph.zip](https://github.com/paritytech/parity-db/files/11378489/flaminggraph.zip)

the file system is ext4 without any configuration, the node is `--state-pruning=archive-canonical --blocks-pruning=archive-canonical`

**Comment by jasl** [comment]
![boot](https://github.com/paritytech/parity-db/assets/1024162/2fc5eda6-1ebe-44c5-9f9d-8664d3b8f7fe)

Upgraded latest parity-db, the slow boot problem exists, here's another flaming graph

**Comment by jasl** [comment]
![exit](https://github.com/paritytech/parity-db/assets/1024162/018ab557-f44a-4039-b84e-28d92dea7b9d)
[exit.svg.zip](https://github.com/paritytech/parity-db/files/11472876/exit.svg.zip)

Here's another flaming graph for the node stuck on exiting

**Comment by arkpar** [comment]
> Upgraded latest parity-db, the slow boot problem still exists (it takes about 8 minutes to start the node which using Azure premium SSD), here's another flaming graph

Are you sure this database was created with parity-db 0.4.7? Previous versions created a long queue of write-ahead log files that would take a long time to process on start. So if you already a database created by an older version and open it with 0.4.7, it will be slow the first time.

**Comment by jasl** [comment]
> > Upgraded latest parity-db, the slow boot problem still exists (it takes about 8 minutes to start the node which using Azure premium SSD), here's another flaming graph
> 
> Are you sure this database was created with parity-db 0.4.7? Previous versions created a long queue of write-ahead log files that would take a long time to process on start. So if you already a database created by an older version and open it with 0.4.7, it will be slow the first time.

I can confirm I'm using 0.4.7, and I have removed the old database before I do the new sync.

The boot time is faster than the previous version (the previous will take more than half an hour to start, 0.4.7 about 7 minutes)

**Comment by arkpar** [comment]
What does `ls -alh log*` show inside `chains/polkadot/paritydb/full/` dir before the slow start?
