### ISSUE TITLE
Question: File size and spread

### ISSUE THREAD

**Issue by crystalin** [paritytech/parity-db#208]
I've been looking at the files using paritydb on an archive node, and saw that it is not well spread.

```
--- /chains/moonbeam/paritydb/full -------------------------------------------------------------------------------------------
                         /..
  295.7 GiB [##########]  table_01_6a
   32.1 GiB [#         ]  index_01_26
   23.2 GiB [          ]  table_01_67
   12.8 GiB [          ]  table_01_65
   12.3 GiB [          ]  table_01_6c
   11.8 GiB [          ]  table_01_39
   11.4 GiB [          ]  table_01_2a
   10.9 GiB [          ]  table_01_2e
   10.1 GiB [          ]  table_01_2f
   10.0 GiB [          ]  table_01_35
    9.3 GiB [          ]  table_01_a2
    8.7 GiB [          ]  table_01_62
    8.4 GiB [          ]  table_01_6b
    8.3 GiB [          ]  table_01_3d
    7.9 GiB [          ]  table_01_60
    7.0 GiB [          ]  table_01_44
    6.6 GiB [          ]  table_01_5a
    ...
    ```
    
    Is it expected ?

**Comment by arkpar** [comment]
Each table_* file contains records of fixed size. `table_01_6a` in particualr contains records of size 562 to 577 bytes. `6a`
 being an index in [this table](https://github.com/paritytech/parity-db/blob/084ef6ac5eaef96dc23223a89ccb43486ace3eba/src/column.rs#L55). Record size is basically value size + ~32 bytes of overhead. The majority of trie nodes happen to be around this 540 bytes. From the database POV, distribution here does not really affect anything.

**Comment by crystalin** [comment]
Thank you for the clarification :)
