### ISSUE TITLE
Support `BTreeIterator` going backwards

### ISSUE THREAD

**Issue by i1i1** [paritytech/parity-db#72]
`BTreeIterator` is iterating over b-tree. So it would be handy to have `.prev()` method which would go backwards on the tree.

**Comment by nazar-pc** [comment]
We can contribute implementation, just need confirmation this is a welcome change to the ParityDb API :slightly_smiling_face: 

We found ParityDb is a good fit for some other blockchain-related use cases outside of the state database, but reverse iteration is hard requirement there.

**Comment by arkpar** [comment]
No objections if you want to make PR.

It should be noted however that BTree columns are not well optimized for storing a lot of data. These were introduced as a temporary solution to store some additional small values in polkadot. Hash indexes should be used whenever possible.

**Comment by nazar-pc** [comment]
We'll store 8 to 32 byte values, so should be fine

**Comment by nazar-pc** [comment]
PR: https://github.com/paritytech/parity-db/issues/72
