### ISSUE TITLE
iter_column_while doesn't return correct number of elements

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/parity-db#81]
Simple test case:
```rust
#[test]
fn iter_column_while() {
    for n in 0..10000 {
        let dir = tempfile::TempDir::new().unwrap();
        let options = parity_db::Options::with_columns(dir.path(), 1);
        let db = parity_db::Db::open_or_create(&options).unwrap();

        let keys = vec![[0u8; 32], [1u8; 32], [2u8; 32], [3u8; 32], [4u8; 32]];

        let tx = keys.iter().map(|key| (0, key, Some(key.to_vec())));
        db.commit(tx).unwrap();

        for key in &keys {
            assert!(db.get(0, key).unwrap().is_some());
        }

        let mut keys_count = 0;
        db.iter_column_while(0, |_iter_state| {
            keys_count += 1;

            true
        })
            .unwrap();

        assert_eq!(keys_count, 5, "iteration {}", n);
    }
}
```

Fails with error like this:
```
---- object_mappings::tests::iter_column_while stdout ----
---- object_mappings::tests::iter_column_while stdout ----
thread 'object_mappings::tests::iter_column_while' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `5`: iteration 29', crates/subspace-farmer/src/object_mappings/tests.rs:152:9
```

Number of elements read can vary, for instance with these 5 keys, hashing disabled and salt set to zero iterator returns no elements at all:
```
0061277d94811d9d65f82e9d267ae62a00219382f109cb4ca806ee0f9d6c2eb5
0061277d94811d9d65f82e9d267ae62a00219382f109cb4ca806ee0f9d6c2eb8
0061277d94811d9d65f82e9d267ae62a00219382f109cb4ca806ee0f9d6c2eba
0061277d94811d9d65f82e9d267ae62a00219382f109cb4ca806ee0f9d6c2ebb
0061277d94811d9d65f82e9d267ae62a00219382f109cb4ca806ee0f9d6c2ece
```

**Comment by nazar-pc** [comment]
On a similar note I found it odd that I need to use this method instead of `iter()` depending on column type. Almost complete lack of any documentation doesn't help much either, but at least source code is available for inspection.

**Comment by cheme** [comment]
Will look at it first thing next monday (maybe before). Just to be sure, in you code snippet there is only 4 distinct key, so it should indeed return 4.

**Comment by nazar-pc** [comment]
Yes, sorry. BTree seems to be fine once I have 5 distinct keys, but regular map iteration still fails with some probability.
Updates test case a bit, usually takes under 100 iterations to fail.

**Comment by cheme** [comment]
Please notice that regular map iteration should only be used in `migration` context, the db needs to be cold (nothing in commit overlay, everything should be flushed first, maybe it works with the log overlay but it is better to flush it just in case).
We use it with parity-db-admin (which flush log first), and is usable to migrate content of a column, but it is currently not intended to work on a live db.

**Comment by nazar-pc** [comment]
There doesn't seem to be a public method for flushing on `Db` struct. My use case requires rate iteration over the collection, so I can flush things before that is there was an API for that.

Would be great if `.iter()` worked on both kinds of columns as is though, doing flushing internally if necessary. Right now it isn't a particularly misuse resistance API.

**Comment by cheme** [comment]
Yes, flushing is asynch, I do it like this for testing purpose:
```
EnableCommitPipelineStages::DbFile => {
				let _ = db.log.flush_one(0).unwrap();
				let _ = db.log.flush_one(0).unwrap();
				while db.enact_logs(false).unwrap() {}
				let _ = db.log.flush_one(0).unwrap();
				let _ = db.clean_logs().unwrap();
			},
```
and there is similar code on shutdown.
I did think of allowing commit to have a callback on WAL flush (which would allow implementing the flushing).
I don't think it is a bad thing as it could be usefull in some case. But that is not a good reply to your usecase.

For implementing, it would need some change of design, I don't remember if log overlay is used when doing iter_while, but the real change needed would be to iter_while on the commit overlay too: would need the hash map of the commit overlay to use blake hash which would reduce performance maybe significantly (except for column with `uniform` true (directly use hash)).

Short term solution may be to have an api for flush (but could take rather long).

Generally current design is to not allow iteration (except for btree index obviously).

@arkpar any other ideas?

**Comment by arkpar** [comment]
`iter_column_while` shouldn't be in the public API in the first place.  It is intenede for migrations which are perormed internally.  In general, iterating a hash column won't yield original keys, unless `preimage` option is set. By defaule the database does not store original keys, only their hashes.

@nazar-pc what's your use case `iter_column_while`?

**Comment by nazar-pc** [comment]
I have a use case for storing unordered keys, but from time to time I want to iterate over all keys and do batched cleanup of some keys. So any iteration in whatever order would work here as long as it is exhaustive.

**Comment by arkpar** [comment]
You'd have to manage the cleanup on a higher level somehow. E.g. journal a set of keys that would need to be cleaned up at some later point. As I've said, retrieving keys from the hash column is not possible in general and is not a design goal.

**Comment by nazar-pc** [comment]
Well, that is unfortunate, thanks for clarifying. Then solution here is indeed to hide method from public API.

**Comment by nazar-pc** [comment]
In my case keys are random, so I was using `uniform = true` and set salt to all zeroes to not mangle keys.

**Comment by arkpar** [comment]
Made private in eb0bf1ea0731ec44c95ed2b59c7e5b17284a72c7
